In [35]:
import numpy as np
import math
from numpy.ma.core import reshape
from numpy.matrixlib.defmatrix import matrix

In [36]:
# Create an array from a list
A = np.array([1,5,3,8,7,6])
print("Array A:-\n", A)

Array A:-
 [1 5 3 8 7 6]


In [37]:
# Create an array with evenly spaced values
B = np.arange(0,10,2)
print("Array B:-\n",B)  

Array B:-
 [0 2 4 6 8]


In [38]:
# Create an array with linearly spaced values
C1 = np.linspace(0,20,5,)                    # 5 values evenly spaced between 0 and 20
print("Array C1:-\n",C1)
C2 = np.linspace(10,30,5,dtype=int)          # 5 values evenly spaced between 10 and 30 (integer)
print("Array C2:-\n",C2)

Array C1:-
 [ 0.  5. 10. 15. 20.]
Array C2:-
 [10 15 20 25 30]


In [39]:
# Create an array filled with zeros
D1 = np.zeros((2, 3))                                         # 2x3 array of zeros
print("Array D1:-\n", D1)
D2 = np.zeros((2, 3),dtype=int)                        # 2x3 array of zeros (integer)
print("Array D2:-\n", D2)

Array D1:-
 [[0. 0. 0.]
 [0. 0. 0.]]
Array D2:-
 [[0 0 0]
 [0 0 0]]


In [40]:
# Create an array filled with ones
E1 = np.ones((3, 2))                                          # 3x2 array of ones
print("Array E1:-\n", E1)
E2 = np.ones((3, 2),dtype=int)                                # 3x2 array of ones (integers)
print("Array E2:-\n", E2)

Array E1:-
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array E2:-
 [[1 1]
 [1 1]
 [1 1]]


In [41]:
# Create an identity matrix
F = np.eye(4,dtype=int)                                    # 4*4 identity matrix
print("Identity Matrix:-\n",F)

Identity Matrix:-
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [42]:
# Reshape an array
G = np.array([1,5,9,7])
g = np.reshape(G,(1,4))                                 # Reshape into 1*4 array
print("Reshaped Array:-\n",g)

Reshaped Array:-
 [[1 5 9 7]]


In [43]:
# Flatten an array
H = np.array([[1,7],[2,3]])
h = np.ravel(H)                                                # Flattens into 1D array
print("Flattened Array:-\n",h)

Flattened Array:-
 [1 7 2 3]


In [44]:
# Transpose an array
I = np.array([[1,2,3],[4,5,6],[7,8,9]])
i = np.transpose(I)
print("Transpose Array:-\n",i)

Transpose Array:-
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
# Stack arrays vertically
J1 = np.array([1,2,3])
J2 = np.array([4,5,6])                                         # Stacks J1 vertically upon J2
j = np.vstack([J1,J2])
print("Stacked Array:-\n",j)

Stacked Array:-
 [[1 2 3]
 [4 5 6]]


In [46]:
# Add 2 to each element of an array
K = np.array([1,2,3,4])
k = np.add(K,2)
print("Added 2 to Array:-",k)

Added 2 to Array:- [3 4 5 6]


In [47]:
# Square each element of an array
M = np.array([1,2,3])
m = np.pow(M,2)
print("Square of Array:- ",m)

AttributeError: module 'numpy' has no attribute 'pow'

In [48]:
# Cube each element of an array
N = np.array([0,1,2])
n = np.pow(N,3)
print("Cube of Array:- ",n)

AttributeError: module 'numpy' has no attribute 'pow'

In [34]:
# Root each element of an array
O = np.array([4,9,16,25,36])
o = np.sqrt(O)
print("Square root of Array:- ",o)

Square root of Array:-  [2. 3. 4. 5. 6.]


In [49]:
# Dot product of 2 arrays
P1 = np.array([3,4,5])
P2 = np.array([6,7,8])
P3 = np.array([1,2,3,9])
p = np.dot(P1,P2)
# np.dot(P1,P3) --> Error
# np.dot(P2,P3) --> Error
print("Dot product of P1 & P2:- ",p)

Dot product of P1 & P2:-  86


In [50]:
# Mean of an array
Q = np.array([2,5,6,9])
q = np.mean(Q)
print("Mean of array:- ",q)

Mean of array:-  5.5


In [51]:
# Standard deviation of an array
R = np.array([4,6,8,5])
r = np.std(R)
print("Standard Deviation of  Array:- ",r)

Standard Deviation of  Array:-  1.479019945774904


In [52]:
# Minimum element of an array
S = np.array([5,4,9,6,3])
s = np.min(S)
print("Min of s:- ", s)

Min of s:-  3


In [56]:
# Create a Matrix
matrix = np.array([[9,2,3],[4,8,6],[7,1,9]])
print(matrix)

[[9 2 3]
 [4 8 6]
 [7 1 9]]


In [57]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:- ",determinant)

Determinant of matrix:-  450.00000000000045


In [ ]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:-\n",inverse)

In [58]:
# # Generate random values between 0 and 1
U = np.random.rand(3)
print("Randon values:- ",U)                                     # Array of 3 random values between 0 and 1

Randon values:-  [0.55388082 0.50838801 0.53078729]


In [59]:
np.random.seed(0)    

In [60]:
V = np.random.rand(3)
print("Randon values seed:- ",V)

Randon values seed:-  [0.5488135  0.71518937 0.60276338]


In [61]:
# Generate random integers
W = np.random.randint(0, 10, 5 )                 # Random integers between 0 and 10
print("Random integers:", W)

Random integers: [3 7 9 3 5]


In [ ]:
np.random.seed(0)                                               # Setting seed for reproducibility
X = np.random.randint(0, 10, 5 )                 # Random integers between 0 and 10
print("Random integers:", X)

In [64]:
logical_test = np.array([True, False, True])

# Check if any elements are True
any_true = np.any(logical_test)
print("Any elements True:", any_true)

# Check if all elements are True
all_true = np.all(logical_test)
print("All elements True:", all_true)

Any elements True: True
All elements True: False


In [65]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])

# Intersection of two arrays
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)


Intersection of a and b: [3 4]
Union of a and b: [1 2 3 4 5 6]
