In [1]:
import cv2
import numpy as np
import os

In [2]:
# Update path to your image
img = cv2.imread(r"C:\Users\nikhi\PycharmProjects\NARESH_IT\PROJECTS_NARESH_IT\Haar_Casade_Classification\Ragdoll.jpg")

# Check what we got
print(img)

[[[ 44  80 120]
  [ 44  80 120]
  [ 44  80 120]
  ...
  [175 167 168]
  [175 167 168]
  [174 166 167]]

 [[ 44  80 120]
  [ 44  80 120]
  [ 44  80 120]
  ...
  [175 167 168]
  [175 167 168]
  [174 166 167]]

 [[ 44  80 120]
  [ 44  80 120]
  [ 44  80 120]
  ...
  [175 167 168]
  [175 167 168]
  [174 166 167]]

 ...

 [[ 98 119 146]
  [ 98 119 146]
  [ 98 119 146]
  ...
  [ 39  58  91]
  [ 39  58  91]
  [ 39  58  91]]

 [[ 98 119 146]
  [ 98 119 146]
  [ 98 119 146]
  ...
  [ 39  58  91]
  [ 39  58  91]
  [ 39  58  91]]

 [[ 98 119 146]
  [ 98 119 146]
  [ 98 119 146]
  ...
  [ 39  58  91]
  [ 39  58  91]
  [ 39  58  91]]]


In [3]:
# Show image in a window

cv2.imshow('Elephant', img)                           # to open a new window and show image
cv2.waitKey()                                         # waits for a key press (otherwise window closes immediately)
cv2.destroyAllWindows()                               # closes the window

In [5]:
# Image Properties

print('Height of Image:', int(img.shape[0]), 'pixels')
print('Width of Image:', int(img.shape[1]), 'pixels')

Height of Image: 747 pixels
Width of Image: 1328 pixels


In [6]:
# Save the image

cv2.imwrite('Op1.PNG', img)

True

In [7]:
current_dir = os.getcwd()
print("Current Working Directory:", current_dir)

Current Working Directory: C:\Users\nikhi
