In [3]:
import numpy as np
print(np.__version__)


1.26.4


In [4]:
myList=[1,2,5,4,8,4,6,5,3]
print(type(myList))

<class 'list'>


In [5]:
arr=np.array(myList)                             # Converting a list into an array
print(type(myList))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
print(np.arange(10))  

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(np.arange(5.0))  

[0. 1. 2. 3. 4.]


In [8]:
print(np.arange(10,20)) 

[10 11 12 13 14 15 16 17 18 19]


In [9]:
print(np.arange(20,10)) 
# [] ----> Always 1st arg < 2nd arg

[]


In [10]:
print(np.arange(-16,1))

[-16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0]


In [11]:
print(np.arange(10,40,3)) 

[10 13 16 19 22 25 28 31 34 37]


In [12]:
print(np.arange(10,40,3))

[10 13 16 19 22 25 28 31 34 37]


In [13]:
print(np.zeros(5))    

[0. 0. 0. 0. 0.]


In [14]:
print(np.zeros(10,dtype=int)) 

[0 0 0 0 0 0 0 0 0 0]


In [15]:
print(np.zeros((2,2)))  

[[0. 0.]
 [0. 0.]]


In [16]:
print(np.zeros((2,2), dtype=int))

[[0 0]
 [0 0]]


In [17]:
print(np.zeros((3,4), dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [18]:
print(np.ones(7)) 

[1. 1. 1. 1. 1. 1. 1.]


In [19]:
print(np.ones((3,3)))   

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(np.ones((3,5),dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
print(np.random.rand(5)) 

[0.18820717 0.0972665  0.84195808 0.55962332 0.57706939]


In [22]:
print(np.random.rand(2,3))

[[0.22988332 0.74915728 0.93169736]
 [0.2886247  0.97536278 0.35448159]]


In [23]:
print(np.random.randint(5,16))

8


In [24]:
print(np.random.randint(0,21,4))

[ 6 20 20  4]


In [25]:
print(np.random.randint(0,1)) 

0


In [26]:
print(np.random.randint(10,40,(10,10)))

[[36 37 20 22 16 14 27 22 10 25]
 [32 30 39 19 35 27 29 23 21 19]
 [13 27 30 38 39 11 32 37 29 25]
 [39 34 27 15 30 38 18 33 35 13]
 [37 38 23 39 36 20 26 28 25 36]
 [33 22 26 38 39 30 30 12 11 10]
 [19 29 34 17 33 34 18 20 19 31]
 [38 10 17 30 22 14 35 21 10 36]
 [19 36 13 19 32 33 15 22 29 25]
 [28 32 28 27 13 31 34 34 30 30]]


In [27]:
print(np.arange(1,13).reshape(3,4)) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(np.arange(1,13).reshape(5,4))

ValueError: cannot reshape array of size 12 into shape (5,4)

In [30]:
print(np.arange(1,13).reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [32]:
A= np.random.randint(10,20,(4,5))
B= np.arange(0,100).reshape(10,10)
C= np.arange(0,16).reshape(4,4)
print(A)
print(type(A))

[[17 16 16 16 12]
 [19 11 15 17 14]
 [17 14 15 10 15]
 [12 12 18 16 17]]
<class 'numpy.ndarray'>


In [33]:
print(A[:])

[[17 16 16 16 12]
 [19 11 15 17 14]
 [17 14 15 10 15]
 [12 12 18 16 17]]


In [34]:
print(A[1:3]) 

[[19 11 15 17 14]
 [17 14 15 10 15]]


In [35]:
print(A[1,3])  

17


In [36]:
print(A[1,-1])  

14


In [37]:
print(A[-2,1])   

14


In [38]:
print(A[-4,3]) 

16


In [39]:
print(A[::-1])  

[[12 12 18 16 17]
 [17 14 15 10 15]
 [19 11 15 17 14]
 [17 16 16 16 12]]


In [45]:
print(B)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [40]:
print(B[::2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]]


In [41]:
print(B[::3])

[[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]
 [60 61 62 63 64 65 66 67 68 69]
 [90 91 92 93 94 95 96 97 98 99]]


In [42]:
print(B[::-1])

[[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [43]:
print(B[::-2])

[[90 91 92 93 94 95 96 97 98 99]
 [70 71 72 73 74 75 76 77 78 79]
 [50 51 52 53 54 55 56 57 58 59]
 [30 31 32 33 34 35 36 37 38 39]
 [10 11 12 13 14 15 16 17 18 19]]


In [44]:
print(B[::-3])

[[90 91 92 93 94 95 96 97 98 99]
 [60 61 62 63 64 65 66 67 68 69]
 [30 31 32 33 34 35 36 37 38 39]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [46]:
print(B[:,6])

[ 6 16 26 36 46 56 66 76 86 96]


In [47]:
print(B[2:6,2:4])  

[[22 23]
 [32 33]
 [42 43]
 [52 53]]


In [48]:
print(B[1:2,2:4]) 

[[12 13]]


In [49]:
print(B.max())

99


In [50]:
print(B.min())

0


In [51]:
print(B.mean())

49.5


In [53]:
print(C>8)

[[False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [56]:
print(B[B>55])

[56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79
 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
